apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoArgocd
  labels:
    app: demoArgocd
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: demoArgocd
  template:
    metadata:
      labels:
        app: demoArgocd
    spec:
      containers:
        - name: demoArgocd
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
